# Generated by Django 4.0.5 on 2022-09-20 00:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0014_article_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentlikes',
            field=models.ManyToManyField(blank=True, null=True, related_name='commentlikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
